### PR TITLE
Added support for Multimodal eval

### PR DESCRIPTION
**Pull request by anirudhs001**
PR for https://github.com/pytorch/torchchat/issues/1334

Used [`VLMEvalWrapper`](https://github.com/pytorch/torchtune/blob/2128559bd182daf3aa056a7cceefcfc135460b0f/recipes/eleuther_eval.py#L40) and [`Llama3VisionTransform`](https://github.com/pytorch/torchtune/blob/8c9235e2b10cc9e1aa381aaec4b992dbf52c48da/torchtune/models/llama3_2_vision/_transform.py#L17C7-L17C28) from torchtune to support evaluation for multimodal models (llama3.2 11b only for now).

Bumped up lm_eval to `lm_eval==0.4.7` to use [`HFMultimodalLM`](https://github.com/EleutherAI/lm-evaluation-harness/blob/4c26a9c176ecfb40b369503ce211e356bb800fdc/lm_eval/models/hf_vlms.py#L31), the class that `VLMEvalWrapper` inherits from.

A sample run for mmmu_val_art:
```
(venv) anirudhsingh@Anirudhs-MacBook-Pro-4 torchchat % python torchchat.py eval Llama-3.2-mm --device cpu --dtype bf16 --task mmmu_val_art --modality text-image --max-seq-length 2048 
NumExpr defaulting to 12 threads.
PyTorch version 2.7.0.dev20250124 available.
Looking for libcustom_ops_aot_lib.so in /Users/anirudhsingh/MISC/playground/torchchat/venv/lib/python3.10/site-packages/executorch
Loading custom ops library: /Users/anirudhsingh/MISC/playground/torchchat/venv/lib/python3.10/site-packages/executorch/extension/llm/custom_ops/libcustom_ops_aot_lib.dylib
Unable to import torchao experimental quant_api with error:  [Errno 2] No such file or directory: '/Users/anirudhsingh/MISC/playground/torchchat/torchao-build/src/ao/torchao/experimental/quant_api.py'
Modality of model=text-image
Using device=cpu
Loading model...
Time to load model: 0.25 seconds
-----------------------------------------------------------
Building contexts for mmmu_val_art on rank 0...
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 30/30 [00:00<00:00, 20148.78it/s]
Running generate_until requests
Running generate_until requests with text+image input: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 30/30 [7:49:19<00:00, 938.65s/it]
Time to run eval: 28171.31s.
Time in model.forward: 28154.47s, over 30 model evaluations
forward run time stats - Median: 360.38s Min: 355.40s Max: 8932.57s
For model /Users/anirudhsingh/.torchchat/model-cache/meta-llama/Llama-3.2-11B-Vision-Instruct/model.pth
mmmu_val_art:
 alias: Art
 acc,none: 0.2333
 acc_stderr,none: 0.0785
```
And with a limit of 1 sample:
```
(venv) anirudhsingh@Anirudhs-MacBook-Pro-4 torchchat % python torchchat.py eval Llama-3.2-mm --device cpu --dtype bf16 --task mmmu_val_art --limit 1 --modality text-image --max-seq-length 720
NumExpr defaulting to 12 threads.
PyTorch version 2.7.0.dev20250124 available.
Looking for libcustom_ops_aot_lib.so in /Users/anirudhsingh/MISC/playground/torchchat/venv/lib/python3.10/site-packages/executorch
Loading custom ops library: /Users/anirudhsingh/MISC/playground/torchchat/venv/lib/python3.10/site-packages/executorch/extension/llm/custom_ops/libcustom_ops_aot_lib.dylib
Unable to import torchao experimental quant_api with error:  [Errno 2] No such file or directory: '/Users/anirudhsingh/MISC/playground/torchchat/torchao-build/src/ao/torchao/experimental/quant_api.py'
Modality of model=text-image
Using device=cpu
Loading model...
Time to load model: 0.25 seconds
-----------------------------------------------------------
Building contexts for mmmu_val_art on rank 0...
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 5159.05it/s]
Running generate_until requests
Running generate_until requests with text+image input: 100%|██████████████████████████████████████████████████████████████| 1/1 [08:38<00:00, 518.97s/it]
Time to run eval: 531.16s.
Time in model.forward: 518.80s, over 1 model evaluations
forward run time stats - Median: 518.80s Min: 518.80s Max: 518.80s
For model /Users/anirudhsingh/.torchchat/model-cache/meta-llama/Llama-3.2-11B-Vision-Instruct/model.pth
mmmu_val_art:
 alias: Art
 acc,none: 0.0000
 ```

### CODE REVIEW

File: torchchat/usages/eval.py [hunk 1]
```diff
@@ -223,6 +482,57 @@ def eval(
     return eval_results
 
 
+def multi_model_eval(
```
Comment (Jack-Khuu) [inline torchchat/usages/eval.py:485]: Looks like this and `eval()` are fairly similar. Mind combining them?

**Comment by anirudhs001** [comment]
@Jack-Khuu sorry for the delay
I've made changes from your comments. Forgot to remove the modality arg from BuilderArgs, did that in the last commit. This should fix the `AttributeError: 'Namespace' object has no attribute 'modality'` failures [[1](https://github.com/pytorch/torchchat/actions/runs/13740844714/job/38429891127?pr=1499),[2](https://github.com/pytorch/torchchat/actions/runs/13740844714/job/38429891013?pr=1499),[3](https://github.com/pytorch/torchchat/actions/runs/13740844714/job/38429893659?pr=1499)...]

Not sure what's wrong in [test-gpu-eval-sanity-check (cuda, stories15M) / linux-job](https://github.com/pytorch/torchchat/actions/runs/13740844714/job/38429893055?pr=1499#logs) though. tried running the test in main on cpu but that fails too for me

**Comment by Jack-Khuu** [comment]
Sorry on the delay on my side as well. I just kicked off the jobs again. Let's see what's going on

**Comment by anirudhs001** [comment]
@Jack-Khuu `lm_eval` is causing the error. The tests on main work fine with `lm_eval==0.4.2`, but fail with `0.4.5+`

**Comment by anirudhs001** [comment]
Found the problem.
While calculating the loglikelihoods, lm_eval prepends a different `prefix_token` now:
It has changed from ([link](https://github.com/EleutherAI/lm-evaluation-harness/blob/4600d6bf73ba2cf7037ae7feada03315839ef185/lm_eval/models/huggingface.py#L818))
```Python
rolling_token_windows = list(
    map(
        utils.make_disjoint_window,
        utils.get_rolling_token_windows(
            token_list=self.tok_encode(string),
            prefix_token=self.eot_token_id,
            max_seq_len=self.max_length,
            context_len=1,
        ),
    )
)
```

to ([link](https://github.com/EleutherAI/lm-evaluation-harness/blob/ebb498e40eb9dd9470e6962915473de0100bcd91/lm_eval/models/huggingface.py#L953))
```Python
rolling_token_windows: List[Tuple[List[int], List[int]]] = list(
    map(
        utils.make_disjoint_window,
        utils.get_rolling_token_windows(
            token_list=self.tok_encode(string),
            prefix_token=self.prefix_token_id,
            max_seq_len=self.max_length,
            context_len=1,
        ),
    )
)
```
HFLM's [`eot_token_id`](https://github.com/EleutherAI/lm-evaluation-harness/blob/ebb498e40eb9dd9470e6962915473de0100bcd91/lm_eval/models/huggingface.py#L400-L402) is `2`, whereas [`prefix_token_id`](https://github.com/EleutherAI/lm-evaluation-harness/blob/ebb498e40eb9dd9470e6962915473de0100bcd91/lm_eval/models/huggingface.py#L405-L411) defaults to `tokenizer.bos_token_id` which is `50256`
There's some module in our test model that limits tokens to be in [0,32000] and throws the `index out of bounds` exception.

**Comment by anirudhs001** [comment]
@Jack-Khuu can you re-run the tests please?

**Review by Jack-Khuu — COMMENTED** [review]
Changes are looking great, we should be good to land soon

--- 

Were you able to validate whether normal `pytorch generate works with the tokenizer changes btw?

https://github.com/pytorch/torchchat/blob/main/docs/multimodal.md

File: torchchat/usages/eval.py [hunk 2]
```diff
@@ -30,9 +30,24 @@
...
+    format_content_with_images,
+    left_pad_sequence,
+    Message,
+    padded_collate_tiled_images_and_mask,
+)
+from torchtune.generation import generate, sample
+
+from torchtune.modules.common_utils import local_kv_cache
+from torchtune.modules.model_fusion import DeepFusionModel
+from torchtune.modules.transforms import Transform
```
[the remark this answers is not in the document]
Comment (Jack-Khuu) [reply torchchat/usages/eval.py]: To avoid scope creeping this PR, how about we undo the tokenizer changes you made `builder.py` and push the tokenizer resolution just within `eval.py` 

For example within eval we can try: 

```
    elif modality == "text-image":
      ... llama3_2_vision_transform(path=str(self.tokenizer_path))
```

File: torchchat/usages/eval.py [hunk 3]
```diff
@@ -168,6 +171,269 @@ def _model_generate(self, context, max_length, eos_token_id):
...
+        format_content_with_images,
+        left_pad_sequence,
+        Message,
+        padded_collate_tiled_images_and_mask,
+    )
+    from torchtune.generation import generate, sample
+
+    from torchtune.modules.common_utils import local_kv_cache
+    from torchtune.modules.model_fusion import DeepFusionModel
+    from torchtune.modules.transforms import Transform
```
Comment (Jack-Khuu) [inline torchchat/usages/eval.py:212]: I think we need this one layer deeper inside of __init__

Class definition is always executed even if an class instance isn't made

Comment (anirudhs001) [reply torchchat/usages/eval.py:212]: > Let's move the imports into VLMEvalWrapper.init()
>
> We're consciously recognizing that doing so is considered bad style, but this reduces the import overhead/requirements for users not using torchtune
>
> (You'll need to update the typehint in the model definition with strings since they don't get defined until init is called)

I did, and then ran a text only eval: `python torchchat.py eval stories15M --dtype fp32 --limit 5` after uninstalling `torchtune`.
It failed because we have `torchtune` imports in `model.py` too:
https://github.com/pytorch/torchchat/blob/4d8bab57ce5dca927402923c2b1ad83cd7e2f6ac/torchchat/model.py#L40-L47

I suppose `model.py` would be used by most/all flows in torchchat. If this is the case, do we still need to move `torchtune` imports inside `VLMEvalWrapper`?

Comment (Jack-Khuu) [reply torchchat/usages/eval.py]: > It failed because we have torchtune imports in model.py too:

This is expected atm, we're still in the process of teasing out the torchtune dependencies, but what you have here will help that effort.

**Comment by Jack-Khuu** [comment]
Thanks for updating the changes!!! I'll give this another test tomorrow and we should be good to merge in

**Review by Jack-Khuu — APPROVED** [review]
Verified on A100

Great work @anirudhs001 merging in
